version: '3.8'

services:

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3307:3306"
    networks:
      - nexora-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5


  nexora-crypto-api:
    build: ./nexora-crypto-api
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - nexora-network

  nexora-crypto-dashboard:
    build: ./nexora-crypto-dashboard/webapps/dashboard
    container_name: frontend
    ports:
      - 4200:80
    networks:
      - nexora-network
    depends_on:
      - nexora-crypto-api

networks:
  nexora-network:
    driver: bridge
