version: '3.8'

services:

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3307:3306"
    networks:
      - nexora-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: crypto_cache
    networks:
      - nexora-network

  nexora-crypto-api:
    image: kousshk/nexora-backend:latest
   # build: ./nexora-crypto-api
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
       mysql:
         condition: service_healthy
    environment:
      - SECURITY_JWT_SECRET_KEY=${SECURITY_JWT_SECRET_KEY}
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - nexora-network

  nexora-crypto-dashboard:
    image: kousshk/nexora-frontend:latest
    #build: ./nexora-crypto-dashboard/webapps/dashboard
    container_name: frontend
    ports:
      - 4200:80
    networks:
      - nexora-network
    depends_on:
      - nexora-crypto-api


networks:
  nexora-network:
    driver: bridge
